from database import SessionLocal, LinkedInPost

db = SessionLocal()

# Batch 3 - More training data
batch3 = [
    "Client: We need a full-featured platform. Skip the MVP nonsense. Me: That'll cost you $200K and 18 months. What if I told you we could validate your idea for $25K in 6 weeks? Client: Impossible. Our competitors took 2 years to build theirs. Here's what happened next... We built their impossible MVP in 37 days. $24,800 total cost. 2 developers + 1 designer. Day 38: They launched to 10 beta users. Day 95: 3,000 signups. Day 102: $15K MRR. What did we build differently? We DID build their core differentiator. We DID build one killer feature beautifully. We DID make it feel like a $1M product. The client called me last week: Client: You saved us 12 months and probably $200k in development costs. Me: Actually, we saved you from building something nobody wanted. Your original idea? The users hated it. The feature that's driving all your growth? That came from week 2 user feedback. If you'd spent 18 months building your original vision, you'd have a $200K product nobody uses. 99% of startups think MVPs are about cutting corners. They're not. MVPs are about cutting risks. The biggest risk isn't building slowly. It's building the wrong thing fast.",
    
    "Technical debt is the most OVERUSED excuse in startups. I've seen engineers refuse to ship features for weeks because of architectural concerns while competitors ate their lunch. After working with 50+ technical teams, here's the reality: Technical debt isn't your biggest problem. Market debt is. The clean code teams I know: Spent 4 months refactoring the foundation. Missed their launch window by 6 months. Built beautiful, unused software. Lost to competitors with inferior architecture. Are now maintaining someone else's messy, profitable codebase. Meanwhile, teams that embraced strategic messiness: Shipped features weekly despite debt. Learned what users actually wanted. Refactored only what customers used. Built profitable products on shaky foundations. Had the luxury of fixing things with revenue. Let me be CLEAR: Perfect code in a failed startup is worthless. What actually happens when you ship despite debt: Users tell you what features matter. Revenue funds proper rebuilds. You learn which debt was actually investment. Technical challenges become good problems. You attract engineers who like solving real problems. The most successful Founder I know: Shipped their first version in PHP. Had 3 different frontend frameworks running simultaneously. Ignored best practices when they slowed shipping. Reached $1M ARR before the great refactor. Now has 50 engineers fixing his profitable mess. Your obsession with technical debt isn't protecting code quality. It's protecting your ego from shipping something imperfect. If your code needs to be perfect before users can see it, you're not building a product. You're building a monument to your own standards. Ship messy or die clean. Your choice.",
    
    "I HATE working with FAANG engineers in early days of startups. Over the past 7+ years, I've managed 100+ engineers. Some came from Google, Facebook, Microsoft. Others came from failed startups, 3-person teams, garage companies. FAANG engineers are optimization machines. Startup engineers are survival machines. Completely different skill sets. FAANG engineer: We need to implement proper caching, set up monitoring, and plan for horizontal scaling. Startup engineer: Let's ship this feature today and see if anyone uses it. Real example from last month: Client needed login system for their MVP. FAANG engineer: Spent 2 weeks building OAuth integration, password encryption, session management, rate limiting. Startup engineer: Used Firebase Auth, done in 2 hours. Both work. One gets you funded. One gets you bankrupt. FAANG engineers solve tomorrow's problems: What if we get 1M users? How do we handle peak traffic? What's our disaster recovery plan? Startup engineers solve today's problems: Will users even sign up? Can we ship before runway ends? What's the fastest way to test this idea? THE RULE: Pre-product-market fit = Hire startup survivors. Post-product-market fit = Hire FAANG scalers. Wrong engineer at wrong stage = death. Your 3-person startup doesn't need Google's infrastructure. It needs to survive until product-market fit. Build fast. Ship faster. Optimize later.",
    
    "Free trials are KILLING your startup. My client just proved it. Everyone screamed: You NEED free trials for SaaS! He did the opposite: $97 upfront, 90-day refund. THE REACTION: You're insane! Nobody will pay! Industry standard is free trials! THE RESULTS: Before: 847 free signups, $3K revenue. After: 124 paid signups, $12K revenue. Same traffic. 4x revenue. Higher satisfaction. Lower churn. Better customers from day one. WHY FREE TRIALS FAIL: Free users don't value your product. They're just killing time. Paying customers? They NEED results. That upfront investment creates commitment. The 90-day refund period actually builds MORE confidence than a 14-day free trial. THE PATTERN: Netflix: Killed free trials, growth exploded. Adobe: Killed free software, revenue 10x'd. Spotify: Free users subsidized by paid users. Don't be afraid to CHALLENGE industry norms. Your WEIRD idea might just be the game-changer YOU need.",
    
    "We fired our best developer yesterday. Not because he wasn't talented. Not because he made mistakes. Not because of budget cuts. We fired him because our client wanted to hire him directly. And we celebrated. When we build MVPs RIGHT, clients want to hire the developers who built them. It means we delivered exactly what we promised. Last year we lost 7 developers this way: 3 joined Series A startups after building their MVPs. 2 joined Fortune 500 innovation labs. 2 became CTOs at the startups we helped launch. Here's what happened: WEEK 8: We delivered their fintech MVP. WEEK 18: Client hits $20K ARR. WEEK 22: Client raises seed round. WEEK 23: We want to hire engineer fulltime. We develop talent, then celebrate when founders steal them. Our retention problem is actually our competitive advantage. Our USP is we don't hire coders. We work with engineers who become founding team members. If you need a coder, please don't disturb me. Check Upwork. If you need engineer who thinks like a startup CEO and executes like a CTO - disturb me."
]

for post in batch3:
    db_post = LinkedInPost(
        post_text=post,
        post_type="training_example"
    )
    db.add(db_post)

db.commit()
print(f'✅ Batch 3 complete! Total: {db.query(LinkedInPost).count()} posts')
db.close()
