from database import SessionLocal, LinkedInPost

db = SessionLocal()

# Batch 4 - Case studies and contrarian takes
batch4 = [
    "No-code platforms are payday loans for startups. My client lost $65,000 because of no-code. Not because his app failed. Because Builder ai went bankrupt and took his entire business with them. Yesterday I got this call: Muhammad, they fired everyone. All 1,500 employees. They're keeping my code hostage and my platform will be dead in days. $65,000. 2 years of work. Gone overnight. That's when it hit me. I've seen this exact playbook before. PAYDAY LOAN COMPANIES: Target desperate people. Quick approval. Lock into payments. Seize everything when they can't pay. NO-CODE PLATFORMS: Target desperate founders. Quick builds. Lock into monthly fees. Business dies when platform dies. Same predatory model. Different industry. I started digging: BUBBLE: Try exporting your app. I dare you. WEBFLOW: Stop paying? Your site dies. BUILDER.AI: Bankrupt? Your $65K is gone. The no-code industry targets the most vulnerable founders. Early-stage. Non-technical. Desperate to ship fast. The exact people who can't afford to lose everything to vendor lock-in. Every successful business faces this question: What happens if our key platform disappears tomorrow? If the answer is our business dies, you don't own a business. You own a lease that can be cancelled anytime. The no-code industry convinced founders that speed matters more than ownership. That's the same logic that drives people to payday loans. I need it now, I'll worry about consequences later. But consequences always come.",
    
    "Your MVP should EMBARRASS you. If you're proud of your first version, you've already failed. We've built 24 MVPs in the last 16 months, and the ones that secured funding all had one thing in common: The founders were EMBARRASSED to show them to customers. Here's what no one tells you about successful MVPs: Our most successful client we built: No authentication system (used magic links only). Spreadsheets powering 40% of automated features. UI that looked like it was designed in 2010. Manual data entry by the founding team behind the scenes. The hard truth? Most founders spend 4-6 extra months building features NOBODY CARES ABOUT. I've seen founders waste $200K+ perfecting features for problems they haven't validated. The most successful technical founders I know all share this mindset: If users aren't begging to use your ugly, broken MVP, a beautiful, polished version won't save you. Your first version should solve ONE core problem so brutally well that users overlook everything else. The best seed investors don't fund perfect products. They fund imperfect products with unmistakable signs of product-market fit. So next time you're thinking just two more weeks to make it better before showing anyone — stop. Launch the version that makes you cringe. Your bank account will thank you later.",
    
    "Your CTO will HATE this story. Story of WORST code that generate $35M. ZERO funding. ZERO engineering experience. ZERO technical co-founders. 600,000+ customers. $30,000,000 in revenue. When Bryan Clayton and his co-founders started GreenPal (the Uber for lawn care), Silicon Valley experts told them their idea would NEVER work without: 1. Raising millions in VC funding. 2. Hiring ex-FAANG engineers. 3. Building sophisticated tech infrastructure. Instead, they did something that would make most founders cringe: Bryan watched YouTube tutorials for 48 hours straight. Built the ENTIRE product themselves on weekends. Launched with what they openly admit was embarrassingly bad code. While Uber for X startups were raising millions and burning cash, GreenPal was building something that actually worked: Year 1: $20K revenue (with terrible code). Year 3: $1M revenue (still terrible code). Year 5: $5M revenue (finally hired engineers to fix it). Year 10: $30M revenue (completely bootstrapped). The result today: 100% bootstrapped. 100% profitable. 100% owned by the founders. 600,000+ active customers. ALL their venture-funded competitors are now dead. What was GreenPal's secret? They obsessed over ONE thing: Customer acquisition cost. While competitors were perfecting their tech stack, GreenPal was: Distributing 400,000 PAPER FLYERS by hand to get their first 100 customers. Going months without founder salaries. Reinvesting 100% of profits back into growth. Targeting small towns while competitors burned cash in major cities. Their technical approach would make any senior engineer quit on the spot: No unit tests. Zero documentation. Spaghetti code that violated every best practice. But it WORKED and MADE MONEY. Here's the thing: Customers didn't care about beautiful architecture or clean code. They cared if their lawn got mowed. Today, GreenPal operates in 300+ cities with 600,000+ customers, while their technically superior competitors have vanished from the market. The most important startup lesson most founders never learn: Ugly code that makes money beats beautiful code that doesn't."
]

for post in batch4:
    db_post = LinkedInPost(
        post_text=post,
        post_type="training_example"
    )
    db.add(db_post)

db.commit()
print(f'✅ Batch 4 complete! Total: {db.query(LinkedInPost).count()} posts')
db.close()
